name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - nightly

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      RASPBERRY_PI_IP: ${{ secrets.RPI_IP_DEV }}
      REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      RASPBERRY_PI_UNAME: ${{ secrets.RASPBERRY_PI_UNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test IPv6 connectivity
        run: ping6 -c 4 google.com
      
      - name: Test IPv6 connectivity
        run: ping6 -c 6 google.com
        
      # - name: Check SSH port with IPv6
      #   run: nc -6 -zv ${{ secrets.RPI_IP_DEV }} 22

      # - name: Setup SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -6 -H ${{ secrets.RPI_IP_DEV }} >> ~/.ssh/known_hosts
          

      # - name: Test SSH connection using IPv6
      #   run: ssh -6 -v ${{ secrets.RASPBERRY_PI_UNAME }}@${{ secrets.RPI_IP_DEV }} exit